# NumPy Giriş
* Numerical Python
* Bilimsel hesaplamalar için kullanılır.
* Arrayler/ çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı    çalışma imkanı sağlar.


## Neden NumPy?


In [5]:
a = [1,2,3,4]
b = [2,3,4,5]

In [6]:
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [9]:
a*b

array([ 2,  6, 12, 20])

### NumPy Array Oluşturmak

In [10]:
import numpy as np

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [16]:
np.array([3.14,4,2,13])
#tek tip veri tutuyor

array([ 3.14,  4.  ,  2.  , 13.  ])

In [18]:
np.array([3.14,4,2,13], dtype = "int")


array([ 3,  4,  2, 13])

In [20]:
#sifirlardan array olusturma
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
#spesifik bir sayidan olusan bir matris olusturma
np.full((3,3),22, dtype = "int")

array([[22, 22, 22],
       [22, 22, 22],
       [22, 22, 22]])

In [23]:
#aritmetik artan dizi
np.arange(0,31,3) 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [24]:
#iki sayi arasinda verilen sayi kadar deger olusturma
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
#normal dagilima uygun ort 10, std sapma 4 olan bir array
np.random.normal(10,4, (3,4))

array([[ 9.58705993,  8.93101666, 11.46950171, 15.24753534],
       [ 9.68887316, 19.0217433 ,  7.79647133,  6.35449336],
       [12.37635615, 10.22654853,  6.11005853, 12.06760671]])

In [28]:
#rasgele integer degerlerden array olusturma
np.random.randint(0,10, (3,3))

array([[7, 9, 6],
       [8, 8, 3],
       [5, 4, 3]])

### Özellikleri

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [30]:
import numpy as np

In [34]:
a = np.random.randint(10, size = 10)
a

array([5, 8, 6, 8, 1, 9, 8, 4, 9, 5])

In [35]:
a.ndim

1

In [36]:
a.shape

(10,)

In [37]:
a.size

10

In [38]:
a.dtype

dtype('int32')

In [40]:
b = np.random.randint(10, size = (3,5))
b

array([[2, 1, 7, 7, 2],
       [1, 5, 6, 4, 3],
       [6, 7, 3, 3, 2]])

In [42]:
b.ndim

2

In [43]:
b.shape

(3, 5)

In [44]:
b.size

15

In [45]:
b.dtype

dtype('int32')

### Yeniden Şekillendirme (reshaping)

In [47]:
import numpy as np

In [50]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
b = a.reshape(1,9)
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
b.ndim

2

### Array Birlestirme (concatenation)

In [55]:
import numpy as np

In [56]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [60]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [61]:
z = np.array([7,8,9])

In [62]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
#iki boyut

In [70]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[7,8,9],
              [10,11,12]])

In [71]:
c = np.concatenate([a,b])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
c.shape

(4, 3)

In [76]:
#axis ile satir veya sutun olarak birlestirmeyi duzenleyebiliriz
#0:satir, 1:sutun
d = np.concatenate([a,b], axis = 1)
d

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [75]:
d.shape

(2, 6)

### Array Ayırma (splitting)

In [77]:
import numpy as np

In [79]:
x = np.array([1,2,3,99,99,3,2,1])

In [80]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [81]:
a,b,c = np.split(x, [3,5])

In [82]:
a

array([1, 2, 3])

In [83]:
b

array([99, 99])

In [84]:
c

array([3, 2, 1])

In [85]:
#iki boyutlu ayirma

In [88]:
m = np.random.randint(13, size = (4,3))
m

array([[ 4, 12, 12],
       [10,  3,  8],
       [ 2,  7,  4],
       [ 9,  7, 10]])

In [90]:
np.vsplit(m,[2])

[array([[ 4, 12, 12],
        [10,  3,  8]]),
 array([[ 2,  7,  4],
        [ 9,  7, 10]])]

In [91]:
ust,alt = np.vsplit(m,[2])

In [93]:
np.concatenate([ust,alt], axis = 1)

array([[ 4, 12, 12,  2,  7,  4],
       [10,  3,  8,  9,  7, 10]])

In [94]:
m

array([[ 4, 12, 12],
       [10,  3,  8],
       [ 2,  7,  4],
       [ 9,  7, 10]])

In [95]:
np.hsplit(m,[2])

[array([[ 4, 12],
        [10,  3],
        [ 2,  7],
        [ 9,  7]]),
 array([[12],
        [ 8],
        [ 4],
        [10]])]

In [96]:
s,t = np.hsplit(m,[2])

### Array Sıralama (sorting)

In [99]:
import numpy as np

In [115]:
v = np.random.randint(100, size = 10)
v

array([80, 13, 23, 26, 27, 76, 64, 36,  4, 21])

In [116]:
np.sort(v)

array([ 4, 13, 21, 23, 26, 27, 36, 64, 76, 80])

In [109]:
#Ikiboyutlu array siralama

In [110]:
m = np.random.normal(20,5, (3,3))
m

array([[26.19564515, 19.25237191, 21.07356695],
       [18.08306217, 15.10622389, 15.37086913],
       [24.12381978, 19.35695343, 19.47452618]])

In [111]:
np.sort(m, axis = 1) #satirlari siraladik

array([[19.25237191, 21.07356695, 26.19564515],
       [15.10622389, 15.37086913, 18.08306217],
       [19.35695343, 19.47452618, 24.12381978]])

In [112]:
np.sort(m, axis = 0) #sutunlari siraladik

array([[18.08306217, 15.10622389, 15.37086913],
       [24.12381978, 19.25237191, 19.47452618],
       [26.19564515, 19.35695343, 21.07356695]])

### Index ile Elemanlara Erişmek

In [114]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([5, 9, 0, 4, 2, 8, 8, 5, 3, 0])

In [117]:
a[0]

5

In [118]:
a[-1]

0

In [120]:
a[2] = 7
a

array([5, 9, 7, 4, 2, 8, 8, 5, 3, 0])

In [121]:
#Iki boyutlu arraylerde elemanlara erisim

In [122]:
b = np.random.randint(10, size = (3,4))
b

array([[2, 5, 3, 7],
       [1, 9, 6, 7],
       [9, 0, 7, 4]])

In [128]:
b[1,0]

1

In [129]:
b[2,3]

4

In [130]:
b[0,0] = 8
b

array([[8, 5, 3, 7],
       [1, 9, 6, 7],
       [9, 0, 7, 4]])

### Slicing ile Elemanlara Erismek (Array Altkümesine Erişmek)

In [131]:
import numpy as np

In [132]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [133]:
a[0:3]

array([20, 21, 22])

In [134]:
a[:3]

array([20, 21, 22])

In [135]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [136]:
a[1::2]

array([21, 23, 25, 27, 29])

In [137]:
a[0::3]

array([20, 23, 26, 29])

In [138]:
#Iki boyutlu slice islemleri

In [140]:
m = np.random.randint(10, size = (5,5))
m

array([[1, 5, 9, 9, 0],
       [9, 4, 8, 9, 7],
       [6, 1, 8, 3, 2],
       [7, 5, 2, 5, 6],
       [1, 0, 1, 5, 7]])

In [144]:
m[:,0] #tum satirlarin 0. sutundaki elemanlari

array([1, 9, 6, 7, 1])

In [142]:
m[:,1] 

array([5, 4, 1, 5, 0])

In [145]:
m[0,:] #0. satirinrin tum sutunlardaki elemanlari

array([1, 5, 9, 9, 0])

In [146]:
m[0] #ilk satir

array([1, 5, 9, 9, 0])

In [147]:
m[1,:]

array([9, 4, 8, 9, 7])

In [148]:
m[0:2,0:3]

array([[1, 5, 9],
       [9, 4, 8]])

In [149]:
m[3:,2:]

array([[2, 5, 6],
       [1, 5, 7]])

In [154]:
m[:,:2] 

array([[1, 5],
       [9, 4],
       [6, 1],
       [7, 5],
       [1, 0]])

### Altküme Üzerinde İşlem Yapmak

In [156]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[4, 1, 9, 6, 0],
       [2, 8, 6, 6, 9],
       [0, 5, 3, 6, 9],
       [9, 2, 8, 7, 4],
       [6, 1, 5, 0, 2]])

In [158]:
alt_a = a[0:3,0:2]
alt_a

array([[4, 1],
       [2, 8],
       [0, 5]])

In [159]:
alt_a[0,0] = 9999
alt_a[1,1] = 8888
alt_a

array([[9999,    1],
       [   2, 8888],
       [   0,    5]])

In [160]:
a

array([[9999,    1,    9,    6,    0],
       [   2, 8888,    6,    6,    9],
       [   0,    5,    3,    6,    9],
       [   9,    2,    8,    7,    4],
       [   6,    1,    5,    0,    2]])

In [161]:
m = np.random.randint(10, size = (5,5))
m

array([[6, 9, 4, 0, 5],
       [6, 8, 4, 9, 9],
       [9, 0, 8, 2, 8],
       [0, 9, 7, 4, 2],
       [0, 2, 0, 3, 3]])

In [163]:
#copy() metodu sectigimiz alt arrayi ana arrayden bagimsizlastirir
alt_b = m[0:3,0:2].copy()
alt_b

array([[6, 9],
       [6, 8],
       [9, 0]])

In [164]:
alt_b[0,0] = 9999
alt_b[1,1] = 8888
alt_b

array([[9999,    9],
       [   6, 8888],
       [   9,    0]])

In [165]:
m

array([[6, 9, 4, 0, 5],
       [6, 8, 4, 9, 9],
       [9, 0, 8, 2, 8],
       [0, 9, 7, 4, 2],
       [0, 2, 0, 3, 3]])

### Fancy Index ile Elemanlara Erişmek

In [166]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [167]:
v[1]

3

In [168]:
v[3]

9

In [169]:
v[5]

15

In [170]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [171]:
indexdeki_elemanlari_getir = [1,3,5]

In [172]:
v[indexdeki_elemanlari_getir]

array([ 3,  9, 15])

In [173]:
#iki boyutta fancy

In [174]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [175]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [176]:
m[satir,sutun]

array([1, 5])

In [178]:
#basit index ile fancy index

In [179]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [180]:
m[0, [1,2]]

array([1, 2])

In [183]:
#slice ile fancy

In [182]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Koşullu Eleman İşlemleri

In [184]:
import numpy as np
v = np.array([1,2,3,4,5])

In [185]:
v > 5 

array([False, False, False, False, False])

In [187]:
v < 3 

array([ True,  True, False, False, False])

In [188]:
v[v < 3]

array([1, 2])

In [189]:
v[v >= 3]

array([3, 4, 5])

In [190]:
v[v == 3]

array([3])

In [191]:
v[v != 3]

array([1, 2, 4, 5])

### Matematiksel İşlemler

In [193]:
import numpy as np
v = np.array([1,2,3,4,5])

In [194]:
v - 1

array([0, 1, 2, 3, 4])

In [195]:
v * 5

array([ 5, 10, 15, 20, 25])

In [196]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [197]:
v**2

array([ 1,  4,  9, 16, 25])

In [198]:
#ufunc 

In [200]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [201]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [202]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [203]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [204]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [205]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [206]:
np.absolute(np.array([-3,-7]))

array([3, 7])

In [207]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [208]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

### İstatistiksel Hesaplamalar

In [209]:
import numpy as np
v = np.array([1,2,3,4,5])

In [210]:
np.mean(v)

3.0

In [211]:
v.sum()

15

In [212]:
v.min()

1

In [213]:
v.max()

5

In [214]:
np.var(v)

2.0

In [215]:
np.std(v)

1.4142135623730951